services:
  grafana:
    build: ./grafana
    environment:
      - GF_USERS_DEFAULT_LANGUAGE=zh-Hans
    ports:
    - 3000:3000
  influx:
    image: influxdb:1.8
    environment:
      - INFLUXDB_DB=health
    volumes:
    - influx-data:/var/lib/influxdb
  ingester:
    build: ./ingester
    volumes:
    - ./tests/test-export.zip:/export.zip

  api:
    build: ./ingester
    command: ["api.py"]
    ports:
    - 5353:5353
    environment:
      - INFLUX_HOST=influx
      - INFLUX_DB=health
      - API_PORT=5353

volumes:
  influx-data: