services:
  grafana:
    image: k0rventen/apple-health-grafana-grafana:v0.6.0
    ports:
    - 3000:3000
  influx:
    image: influxdb:1.12
    environment:
      - INFLUXDB_DB=health
    volumes:
    - influx-data:/var/lib/influxdb
  ingester:
    image: k0rventen/apple-health-grafana-ingester:v0.6.0
    volumes:
    - ./export.zip:/export.zip

volumes:
  influx-data:
