{
 "title": "苹果健康 · 分项指标",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "source",
    "query": "show tag values from \"data-sources\" with key=device"
   }
  ]
 },
 "panels": [
  { "title": "年度活动", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "今年步行/跑步距离",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "步行/跑步距离",
     "groupBy": [
      { "params": [ "unit" ], "type": "tag" }
     ],
     "measurement": "DistanceWalkingRunning",
     "query": "SELECT sum(\"value\") FROM \"DistanceWalkingRunning\" WHERE (\"device\" =~ /^$source$/) AND  time > now() - 365d GROUP BY \"unit\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "今年总步数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "总步数",
     "groupBy": [
      { "params": [ "unit" ], "type": "tag" }
     ],
     "measurement": "DistanceWalkingRunning",
     "query": "SELECT sum(\"value\") FROM \"StepCount\" WHERE (\"device\" =~ /^$source$/) AND  time > now() - 365d GROUP BY \"unit\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "每日活动", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "每日步行距离",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "groupBy": [
      {
       "params": [
        "1d",
        "16h"
       ],
       "type": "time"
      },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "DistanceWalkingRunning",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$source$/" }
     ]
    }
   ]
  },
  {
   "title": "每日骑行距离",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "groupBy": [
      {
       "params": [
        "1d",
        "16h"
       ],
       "type": "time"
      },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "DistanceCycling",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "每日锻炼时长（分钟）",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "groupBy": [
      {
       "params": [
        "1d",
        "16h"
       ],
       "type": "time"
      },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "AppleExerciseTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "每日步数",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "steps" } },
   "targets": [
    {
     "groupBy": [
      {
       "params": [
        "1d",
        "16h"
       ],
       "type": "time"
      },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StepCount",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$source$/" }
     ]
    }
   ]
  },
  {
   "title": "每日爬楼层数",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "flights" } },
   "targets": [
    {
     "groupBy": [
      {
       "params": [
        "1d",
        "16h"
       ],
       "type": "time"
      },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "FlightsClimbed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "每日消耗能量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "alias": "活动能量",
     "groupBy": [
      {
       "params": [
        "1d",
        "16h"
       ],
       "type": "time"
      },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ActiveEnergyBurned",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " * 1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "基础能量",
     "groupBy": [
      {
       "params": [
        "1d",
        "16h"
       ],
       "type": "time"
      },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "BasalEnergyBurned",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " * 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "每日站立时间",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "groupBy": [
      {
       "params": [
        "1d",
        "16h"
       ],
       "type": "time"
      },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "AppleStandTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "平均步行速度",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "groupBy": [
      {
       "params": [
        "1d",
        "16h"
       ],
       "type": "time"
      },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "WalkingSpeed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "心率概况", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "心率概况（按日）",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "targets": [
    {
     "alias": "步行心率",
     "groupBy": [
      {
       "params": [
        "1d",
        "16h"
       ],
       "type": "time"
      },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "WalkingHeartRateAverage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "静息心率",
     "groupBy": [
      {
       "params": [
        "1d",
        "16h"
       ],
       "type": "time"
      },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "RestingHeartRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "每日最低/最高心率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "targets": [
    {
     "alias": "最低心率",
     "groupBy": [
      {
       "params": [
        "1d",
        "16h"
       ],
       "type": "time"
      },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "HeartRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    },
    {
     "alias": "最高心率",
     "groupBy": [
      {
       "params": [
        "1d",
        "16h"
       ],
       "type": "time"
      },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "HeartRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "心率变异性",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      {
       "params": [
        "1d",
        "16h"
       ],
       "type": "time"
      },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "HeartRateVariabilitySDNN",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "每日心率过低/过高事件次数",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "targets": [
    {
     "alias": "低心率事件",
     "groupBy": [
      {
       "params": [
        "1d",
        "16h"
       ],
       "type": "time"
      },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LowHeartRateEvent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "高心率事件",
     "groupBy": [
      {
       "params": [
        "1d",
        "16h"
       ],
       "type": "time"
      },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "HighHeartRateEvent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "全天心率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "活动时长",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AppleExerciseTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "心率",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HeartRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "睡眠数据", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "就寝与入睡时间",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 48 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "device::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SleepAnalysisTimes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$source$/" }
     ]
    }
   ]
  },
  {
   "title": "卧床与睡眠时长",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 10, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "groupBy": [
      {
       "params": [
        "1d",
        "16h"
       ],
       "type": "time"
      },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "device::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "SleepAnalysis",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$source$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "睡眠目标",
     "measurement": "SleepDurationGoal",
     "query": "SELECT \"value\" FROM \"autogen\".\"SleepDurationGoal\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "卧床总时长（$tag_device）",
     "groupBy": [
      { "params": [ "device::tag" ], "type": "tag" }
     ],
     "measurement": "SleepAnalysis",
     "query": "SELECT sum(\"value\") FROM \"autogen\".\"SleepAnalysis\" WHERE (\"state\"::tag = 'HKCategoryValueSleepAnalysisInBed') AND $timeFilter GROUP BY \"device\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "state::tag",
       "operator": "=",
       "value": "HKCategoryValueSleepAnalysisInBed"
      }
     ]
    },
    {
     "alias": "睡眠总时长（$tag_device）",
     "groupBy": [
      { "params": [ "device::tag" ], "type": "tag" }
     ],
     "measurement": "SleepAnalysis",
     "query": "SELECT sum(\"value\") FROM \"autogen\".\"SleepAnalysis\" WHERE (\"state\"::tag = 'HKCategoryValueSleepAnalysisInBed') AND $timeFilter GROUP BY \"device\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "state::tag",
       "operator": "=",
       "value": "HKCategoryValueSleepAnalysisAsleepUnspecified"
      }
     ]
    }
   ]
  }
 ]
}